import type { Aggregates } from '../analytics';

function fmtTime(ms: number) {
  const s = Math.round(ms / 1000);
  return `${Math.floor(s / 60)}:${String(s % 60).padStart(2, '0')}`;
}

export function ReportView({
  agg,
  showName,
  period,
  onClose,
}: {
  agg: Aggregates;
  showName: string;
  period: string;
  onClose: () => void;
}) {
  const k = agg.kpis;
  const topAttention = agg.attention[0]?.title ?? '—';
  const topInterest = agg.interest[0]?.name ?? '—';
  const topVideo = agg.videos[0];

  const summaryText = [
    `Exhibly — Post-show report`,
    `${showName} · ${period}`,
    ``,
    `${k.sessions} visitors engaged the display and ${k.leads} left their details (${k.conversionPct}% conversion).`,
    `Engagement rate ${k.engagementPct}%, average ${fmtTime(k.avgTimeMs)} per session, ${k.videos} how-to videos played.`,
    ``,
    `Held attention longest: ${agg.attention.slice(0, 3).map((a) => `${a.title} (${(a.dwellMs / 1000).toFixed(1)}s)`).join(', ')}.`,
    `Lead interest: ${agg.interest.map((i) => `${i.name} ${i.count}`).join(', ')}.`,
    topVideo ? `Top video: ${topVideo.title} — ${topVideo.plays} plays, ${topVideo.completionPct}% completion.` : '',
    ``,
    `Recommendation: buyers spent the most time on the ${topAttention}; most leads asked about ${topInterest}. Lead follow-up on ${topInterest} and put the ${topAttention} front-and-centre next show.`,
  ].join('\n');

  const emailHref = `mailto:?subject=${encodeURIComponent(`Exhibly report — ${showName}`)}&body=${encodeURIComponent(summaryText)}`;

  return (
    <div className="ins-report-scrim" onClick={onClose}>
      <div className="ins-report" onClick={(e) => e.stopPropagation()}>
        <div className="rbar">
          <span style={{ fontWeight: 700 }}>Executive summary</span>
          <div className="rb">
            <a className="rbtn" href={emailHref}>Email</a>
            <button className="rbtn primary" onClick={() => window.print()}>Print / Save PDF</button>
            <button className="rbtn" onClick={onClose}>Close</button>
          </div>
        </div>
        <div className="body">
          <span className="eyebrow">Post-show report</span>
          <h1 className="serif"><b>{k.sessions}</b> visitors engaged, and <b>{k.leads}</b> left their details — here’s what caught their eye at {showName}.</h1>

          <div className="rrates">
            <div className="rrate"><div className="v">{k.engagementPct}%</div><div className="k">engagement</div></div>
            <div className="rrate"><div className="v">{k.conversionPct}%</div><div className="k">conversion</div></div>
            <div className="rrate"><div className="v">{fmtTime(k.avgTimeMs)}</div><div className="k">avg. time</div></div>
            <div className="rrate"><div className="v">{k.leads}</div><div className="k">leads captured</div></div>
          </div>

          <h3>What held attention</h3>
          {agg.attention.slice(0, 3).map((a) => (
            <div className="rrow" key={a.title}><span>{a.title}</span><span className="m">{(a.dwellMs / 1000).toFixed(1)}s avg · {a.taps} taps</span></div>
          ))}

          <h3>Video &amp; interest</h3>
          {topVideo && <div className="rrow"><span>{topVideo.title}</span><span className="m">{topVideo.plays} plays · {topVideo.completionPct}% completion</span></div>}
          {agg.interest.map((i) => (
            <div className="rrow" key={i.name}><span>{i.name}</span><span className="m">{i.count} leads · {Math.round((i.count / Math.max(1, k.leads)) * 100)}%</span></div>
          ))}

          <div className="rec">
            <b>Recommendation.</b> Buyers spent the most time on the <b>{topAttention}</b>, and most leads asked about <b>{topInterest}</b>. Prioritise {topInterest.toLowerCase()} follow-ups, and lead with the {topAttention.toLowerCase()} in next show’s pitch and collateral.
          </div>

          <div className="foot">Illustrative sample data · {period}. Generated by Exhibly Insights.</div>
        </div>
      </div>
    </div>
  );
}
